name: Deploy Supabase Migrations

on:
  push:
    branches:
      - main
      - acceptance

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Set database URL based on branch
        run: |
          if [ "$GITHUB_REF" == "refs/heads/main" ]; then
            echo "SUPABASE_DB_URL=${{ secrets.SUPABASE_DB_URL_PRODUCTION }}" >> $GITHUB_ENV
          else
            echo "SUPABASE_DB_URL=${{ secrets.SUPABASE_DB_URL_ACCEPTANCE }}" >> $GITHUB_ENV
          fi

      - name: Apply Supabase migrations
        run: supabase db push --db-url $SUPABASE_DB_URL