name: Supabase Migrations SSH Agent Error

on: [workflow_dispatch]

jobs:
  reproduce:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Supabase CLI
        run: |
          npm install -g supabase

      - name: Run Supabase Remote Commit (Expect SSH Agent Error)
        run: |
          unset SSH_AUTH_SOCK
          supabase db remote commit
