name: Reproduce Supabase SSH Agent Error

on: [workflow_dispatch]

jobs:
  test-ssh-agent-error:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Supabase CLI
        run: |
          brew install supabase/tap/supabase
          supabase --version

      - name: Unset SSH agent and run Supabase remote commit
        run: |
          unset SSH_AUTH_SOCK
          supabase db remote commit
