name: Reproduce SSH Agent Error

on: [main]

jobs:
  clone-without-ssh-agent:
    runs-on: ubuntu-latest
    steps:
      - name: Try SSH clone without SSH agent
        run: |
          GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no" git clone git@github.com:jenniekibiri/supabase-migrations.git
